image:
  file: .docker/Dockerfile

ports:
  - port: 6080

tasks:
  - before: dotnet tool restore && dotnet paket restore
  - init: ./fake.sh build -t Build

vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.5.0:0qxXuhq6eO066etkNQrKCQ==
